# Generated by Django 4.2.1 on 2023-05-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BanditModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_col', models.CharField(max_length=100)),
                ('col_offset', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=100)),
                ('issue_confidence', models.CharField(max_length=100)),
                ('issue_cwe', models.CharField(max_length=100)),
                ('issue_severity', models.CharField(max_length=100)),
                ('issue_text', models.CharField(max_length=100)),
                ('line_number', models.CharField(max_length=100)),
                ('line_range', models.CharField(max_length=100)),
                ('more_info', models.CharField(max_length=100)),
                ('test_id', models.CharField(max_length=100)),
                ('test_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('project_id', models.CharField(max_length=10)),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
