# Generated by Django 4.1.7 on 2023-03-19 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_rename_result_banditmodels_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banditmodels',
            old_name='code',
            new_name='code_col',
        ),
    ]
