# Generated by Django 4.1.7 on 2023-03-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_rename_code_banditmodels_code_col'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileZip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='files')),
            ],
        ),
    ]
