version: "3.8"

services:
  nginx:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-frontend
    container_name: lun903-nginx
    ports:
      - "80:80"
    volumes:
      - ../nginx:/etc/nginx/conf.d
      - static_volume:/static
    depends_on:
      - app-lilie-backend
    networks:
      - localnet

  app-lilie-backend:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-lilie
    container_name: lun903-lilie-backend
    expose:
      - "8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - shared-scan:/shared/project_scan
    depends_on:
      - app-db
    networks:
      - localnet

  app-db:
    image: postgres:16.1-alpine@sha256:6cec07cb67f8e819dfe044dd6fc07d87c2c58051f90273d0d8c2611a4d24da16
    container_name: lun903-db
    env_file:
      - ../lilie/.env
    volumes:
      - ../scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - localnet
  
  redis:
    image: redis:7.2.3-alpine@sha256:aa9dc6761b6f8f71796b2ce3700d48472d2ab8a5494a2ff22dc7a0d90d77144e
    hostname: redis
    container_name: lun903-redis
    depends_on:
      - app-lilie-backend
  
  dependency-track:
    image: owasp/dependency-track:latest@sha256:efc65e702ee1691bd9e04bf30a89cae0ee12ec77e9601e9e46b2bcc625e60c0a
    ports:
      - "11488:8080"
    volumes:
      - dependency-track-data:/data
    networks:
      - localnet
    deploy:
      resources:
        limits:
          memory: 8G


volumes:
  shared-scan:
    driver: local
  dependency-track-data:
    driver: local
  postgres_data:
  static_volume:

networks:
  localnet:
    name: localnet
    driver: bridge
