version: '3.8'
services:
  app-db:
    env_file:
      - ../lilie/.env
    image: postgres:latest
    container_name: lun903-db-testing
    ports:
     - 5432:5432
    volumes:
      - ../scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  dependency-track:
    image: owasp/dependency-track:latest@sha256:efc65e702ee1691bd9e04bf30a89cae0ee12ec77e9601e9e46b2bcc625e60c0a
    ports:
      - "11488:8080"
    deploy:
      resources:
        limits:
          memory: 8G

  redis:
    image: redis:7.2.3-alpine@sha256:aa9dc6761b6f8f71796b2ce3700d48472d2ab8a5494a2ff22dc7a0d90d77144e
    hostname: redis
    container_name: lun903-redis
  
  worker:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-lilie
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ../lilie/lilie:/lilie
    links:
      - redis
    depends_on:
      - redis
  
  flower:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-lilie
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - ../lilie/lilie:/lilie
    links:
      - redis
    depends_on:
      - redis
    ports: 
      - '5555:5555'

