version: "3.8"

services:
  nginx:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-frontend
    container_name: lun903-nginx
    ports:
      - "80:80"
    volumes:
      - ../nginx:/etc/nginx/conf.d
      - static_volume:/static
    depends_on:
      - app-lilie-backend
    networks:
      - localnet

  app-lilie-backend:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-lilie
    container_name: lun903-lilie-backend
    expose:
      - "8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - shared-scan:/shared/project_scan
    depends_on:
      - app-db
    networks:
      - localnet

  app-db:
    image: postgres:latest
    container_name: lun903-db
    env_file:
      - ../lilie/.env
    volumes:
      - ../scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - localnet

volumes:
  shared-scan:
    driver: local
  postgres_data:
  static_volume:

networks:
  localnet:
    name: localnet
    driver: bridge
