version: '3.5'
services:
  app-db:
    env_file:
      - ../lilie/.env
    image: postgres:latest
    container_name: lun903-db-testing
    ports:
     - 5432:5432
    volumes:
      - ../scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped