version: "3.5"
services:
  app-lilie-backend:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-lilie
    container_name: lun903-lilie-backend
    ports:
      - 8000:8000
    restart: unless-stopped
    depends_on:
      - app-db
    networks:
      - localnet
  app-db:
    env_file:
      - ../lilie/.env
    image: postgres:latest
    container_name: lun903-db
    ports:
      - 5432:5432
    volumes:
      - ../scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - localnet
networks:
  localnet:
    name: localnet
    driver: bridge