version: '3.8'
services:
  app-db:
    env_file:
      - ../lilie/.env
    image: postgres:latest
    container_name: lun903-db-testing
    ports:
     - 5432:5432
    volumes:
      - ../scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
  
  redis:
    image: redis:alpine@sha256:43076a37580453c7d2516cff8e4aa6b5a8af2c86366ff8b8b4bde0b0b1fb0c32
    hostname: redis
    container_name: lun903-redis-testing
  
  worker:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-lilie
    hostname: worker
    container_name: lun903-worker-testing
    entrypoint: celery
    command: -A core worker --loglevel=info
    volumes:
      - ../lilie:/lilie
      - /var/run/docker.sock:/var/run/docker.sock
      - shared-scan:/shared/project_scan
      - shared-uploads:/lilie/uploads/
    links:
      - redis
    depends_on:
      - redis 
    
  flower:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-lilie
    hostname: flower
    container_name: lun903-flower-testing
    entrypoint: celery
    command: -A core flower
    volumes:
      - ../lilie:/lilie
    links:
      - redis
    depends_on:
      - redis
    ports: 
      - '5555:5555'

volumes:
  shared-scan:
    driver: local
  shared-uploads:
    driver: local
  static_volume:
    driver: local