version: '3.8'
### PROJECT dvpwa ###
services:
  dvpwa-db:
    container_name: dvpwa-db
    image: safdtgxqwe/dvpwa-db:1.0
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
  
  dvpwa-app:
    container_name: dvpwa-app
    image: safdtgxqwe/dvpwa-app:1.1
    command: python run.py
    ports:
      - 8081:8080
    depends_on:
       dvpwa-db:
         condition: service_healthy
       redis:
         condition: service_started
### END dvpwa ###

### PROJECT WebGoat ###
  webgoat:
    container_name: webgoat
    image: webgoat/webgoat
    ports:
      - 9092:9090
### END dvpwa ###

### PROJECT juice-shop ###
  juice-shop:
    container_name: juice-shop
    image: bkimminich/juice-shop
    ports:
      - 3000:3000
### END juice-shop ###

### PROJECT mutillidae ###
  database:
    container_name: database
    image: docker.io/webpwnized/mutillidae:database
    networks:
      - datanet   

  database_admin:
    container_name: database_admin
    depends_on:
      - database
    image: docker.io/webpwnized/mutillidae:database_admin
    ports:
      - 127.0.0.1:81:80
    networks:
      - datanet   

  # Port 8080 is for StackHawk to scan. Use port 8088 for Burp-Suite
  # IP 127.0.0.1 is for mutillidae.localhost or www.mutillidae.localhost
  # IP 127.0.0.1 is for cors.mutilliiidae.localhost
  www:
    container_name: www
    depends_on:
      - database
      - directory
    image: docker.io/webpwnized/mutillidae:www
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:8080:80
      - 127.0.0.1:443:443
      - 127.0.0.2:80:80
      - 127.0.0.2:8080:80
      - 127.0.0.2:443:443
    networks:
      - datanet
      - ldapnet

  directory:
    container_name: directory
    image: docker.io/webpwnized/mutillidae:ldap
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    ports:
      - 127.0.0.1:389:389
    networks:
      - ldapnet

  directory_admin:
    container_name: directory_admin
    depends_on:
      - directory
    image: docker.io/webpwnized/mutillidae:ldap_admin
    ports:
      - 127.0.0.1:82:80
    networks:
      - ldapnet
### END mutillidae ###

### PROJECT DVWA ###
  web-dvwa:
    container_name: web-dvwa
    image: vulnerables/web-dvwa
    ports:
      - 83:80
### END DVWA ###

volumes:
  ldap_data:
  ldap_config:

networks:
    datanet:
    ldapnet: