name: "Build, and deploy"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install dependencies
      run: npm ci
